[package]
authors = ["Asher Jingkong Chen"]
description = "A library to import scenes for `gausplat`"
edition.workspace = true
license-file = "LICENSE"
name = "gausplat-importer"
publish = false
readme = "README.md"
repository = "https://github.com/AsherJingkongChen/gausplat-importer"
version.workspace = true

[dependencies]
burn-tensor = {workspace = true}
bytemuck = {workspace = true}
dashmap = {workspace = true, features = ["rayon"]}
image = {workspace = true, features = ["jpeg", "png", "rayon"]}
indexmap = {workspace = true, features = ["rayon", "std"]}
log = {workspace = true}
rand = {workspace = true, features = ["getrandom", "std_rng"]}
rand_distr = {workspace = true}
rayon = {workspace = true}
thiserror = {workspace = true}
