[package]
authors = ["Asher Jingkong Chen"]
description = "A library to import scenes for `gausplat`"
edition.workspace = true
license-file = "LICENSE"
name = "gausplat-importer"
publish = false
readme = "README.md"
repository = "https://github.com/AsherJingkongChen/gausplat-importer"
version.workspace = true

[dependencies]
bytemuck = {workspace = true, features = ["derive"]}
dashmap = {workspace = true, features = ["rayon"]}
image = {workspace = true}
rayon = {workspace = true}
thiserror = {workspace = true}

[dev-dependencies]
image = {workspace = true, features = ["png"]}
