[package]
description = "A library to import data for gausplat-trainer"
edition = "2021"
name = "gausplat-importer"
publish = false
version = "0.0.0"

[dependencies]
bytemuck = {version = "1.16.1"}
image = { version = "0.25.1", default-features = false }

[dev-dependencies]
anyhow = {version = "1.0.86"}
image = { version = "0.25.1", default-features = false, features = ["jpeg", "png"] }

[profile.dev]
opt-level = 1
