[package]
authors = ["Asher Jingkong Chen"]
description = "A library to import scenes for gausplat-trainer"
edition.workspace = true
license-file = "LICENSE"
name = "gausplat-importer"
publish = false
readme = "README.md"
repository = "https://github.com/AsherJingkongChen/gausplat-importer"
version.workspace = true

[dependencies]
bytemuck = {workspace = true}
dashmap = {workspace = true}
image = {workspace = true}
rayon = {workspace = true}
